FROM python:3

RUN pip install git+git://github.com/guptarohit/cryptoCMD.git
RUN pip install pandas
RUN pip install pip install flask

ADD history.py /usr/local/bin/
ADD today.py /usr/local/bin/

WORKDIR /home/

CMD ["python", "/usr/local/bin/history.py"]
