version: "3.9"

services:
  backend:
    build:
      context: ./
      dockerfile: Dockerfile_backend
    ports:
     - 8082:80
  # frontend:
  #   build:
  #     context: ./
  #     dockerfile: Dockerfile_frontend
  #   ports:
  #    - 3000
  #   command:
  #    - "yarn"
  #    - "start"
      