
node{
   stage('SCM Checkout'){
       git credentialsId: 'github-creds', url: 'https://github.com/garyrizzo1992/crypto-ticker'
   }
//    stage('Mvn Package'){
//      def mvnHome = tool name: 'maven-3', type: 'maven'
//      def mvnCMD = "${mvnHome}/bin/mvn"
//      sh "${mvnCMD} clean package"
//    }
   stage('Build Docker Image'){
     sh  'cd yfinance'
     sh  "docker build -t garyrizzo1992/crypto-ticker:${BUILD_NUMBER} ."
   }
   stage('Push Docker Image'){
     withCredentials([usernamePassword(credentialsId: 'gitlab-creds', usernameVariable: 'user', passwordVariable: 'pass')]) {
        sh  "docker login registry.gitlab.com -u ${user} -p ${pass}"
     }
     sh "docker push garyrizzo1992/crypto-ticker:${BUILD_NUMBER}"
   }
//    stage('Run Container on Dev Server'){
//      def dockerRun = 'docker run -p 8080:8080 -d --name my-app kammana/my-app:2.0.0'
//      sshagent(['dev-server']) {
//        sh "ssh -o StrictHostKeyChecking=no ec2-user@172.31.18.198 ${dockerRun}"
//      }
//    }
}
